
/*
 *    MCreator note: This file will be REGENERATED on each build.
 */
package net.mcreator.papercraftmagicdecoration.init;

import net.minecraftforge.registries.RegistryObject;
import net.minecraftforge.registries.ForgeRegistries;
import net.minecraftforge.registries.DeferredRegister;

import net.minecraft.world.level.block.Block;

import net.mcreator.papercraftmagicdecoration.block.YellowPaperBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.WoodworkingTableBlock;
import net.mcreator.papercraftmagicdecoration.block.WoodenBarrelBookshelfBlock;
import net.mcreator.papercraftmagicdecoration.block.WineAromaRedWallpaperWallsBlock;
import net.mcreator.papercraftmagicdecoration.block.WineAromaBlueWallpaperWallsBlock;
import net.mcreator.papercraftmagicdecoration.block.WhitePaperBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.VodkaBlock;
import net.mcreator.papercraftmagicdecoration.block.UndergroundWallpaperWallsBlock;
import net.mcreator.papercraftmagicdecoration.block.UndergroundPanellingBlock;
import net.mcreator.papercraftmagicdecoration.block.UndergroundDoorFramesBlock;
import net.mcreator.papercraftmagicdecoration.block.UmbrellaCashewFruitingStemBlock;
import net.mcreator.papercraftmagicdecoration.block.UmbrellaCashewBlock;
import net.mcreator.papercraftmagicdecoration.block.ThirdSteakBlock;
import net.mcreator.papercraftmagicdecoration.block.ThirdSalmonBlock;
import net.mcreator.papercraftmagicdecoration.block.SteakTrayBlock;
import net.mcreator.papercraftmagicdecoration.block.StarEmbellishedCeilingBlock;
import net.mcreator.papercraftmagicdecoration.block.SporesCollectionPlateBlock;
import net.mcreator.papercraftmagicdecoration.block.SixthSteakBlock;
import net.mcreator.papercraftmagicdecoration.block.SilverFoodDomeBlock;
import net.mcreator.papercraftmagicdecoration.block.SecondSteakBlock;
import net.mcreator.papercraftmagicdecoration.block.SecondSalmonBlock;
import net.mcreator.papercraftmagicdecoration.block.SausageMaceWeaponBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.SalmonTrayBlock;
import net.mcreator.papercraftmagicdecoration.block.SalmonHeadBlock;
import net.mcreator.papercraftmagicdecoration.block.RusticPanellingBlock;
import net.mcreator.papercraftmagicdecoration.block.RusticBlueWallpaperWallsBlock;
import net.mcreator.papercraftmagicdecoration.block.RoughPalmTreeTrunkBlock;
import net.mcreator.papercraftmagicdecoration.block.RedVelvetChaiseLongueBlock;
import net.mcreator.papercraftmagicdecoration.block.RedPaperBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.RawSausageMaceWeaponBlock;
import net.mcreator.papercraftmagicdecoration.block.RawMonsterSteakBlock;
import net.mcreator.papercraftmagicdecoration.block.RawMangaMeatBlock;
import net.mcreator.papercraftmagicdecoration.block.PotOfNocturnalCatCoffeeBlock;
import net.mcreator.papercraftmagicdecoration.block.PotOfGoldMedalCoffeeBlock;
import net.mcreator.papercraftmagicdecoration.block.PotOfBoiledNocturnalCatCoffeeBlock;
import net.mcreator.papercraftmagicdecoration.block.PotOfBoiledGoldMedalCoffeeBlock;
import net.mcreator.papercraftmagicdecoration.block.PoisonRumBlock;
import net.mcreator.papercraftmagicdecoration.block.PaperCuttingTableBlock;
import net.mcreator.papercraftmagicdecoration.block.PalmTreeTrunkTopBlock;
import net.mcreator.papercraftmagicdecoration.block.PalmTreeTrunkBlock;
import net.mcreator.papercraftmagicdecoration.block.PalmTreeTopBlock;
import net.mcreator.papercraftmagicdecoration.block.PalmTreeCrownBlock;
import net.mcreator.papercraftmagicdecoration.block.PairOfLandNo1ByTheGlassBlock;
import net.mcreator.papercraftmagicdecoration.block.PairOfLandNo1ByTheGlassAfterMovingBlock;
import net.mcreator.papercraftmagicdecoration.block.PaintingNo3FirstEncounterBlock;
import net.mcreator.papercraftmagicdecoration.block.PaintingNo2AoaoBlock;
import net.mcreator.papercraftmagicdecoration.block.PaintingNo1BunnyMaidBlock;
import net.mcreator.papercraftmagicdecoration.block.PackOfGuangSBlock;
import net.mcreator.papercraftmagicdecoration.block.OrganPlayingBlock;
import net.mcreator.papercraftmagicdecoration.block.OldOrganBlock;
import net.mcreator.papercraftmagicdecoration.block.NocturnalCatCoffeeBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.MiniPalmTreeBlock;
import net.mcreator.papercraftmagicdecoration.block.MarbleAngelBlock;
import net.mcreator.papercraftmagicdecoration.block.MangaMeatGrillBlock;
import net.mcreator.papercraftmagicdecoration.block.MangaMeatBlock;
import net.mcreator.papercraftmagicdecoration.block.LuckyCactusBlock;
import net.mcreator.papercraftmagicdecoration.block.LowcabinetWithTableclothBlock;
import net.mcreator.papercraftmagicdecoration.block.LoudButtonBlock;
import net.mcreator.papercraftmagicdecoration.block.LongStorageTableBlock;
import net.mcreator.papercraftmagicdecoration.block.LargeDiningTableBlock;
import net.mcreator.papercraftmagicdecoration.block.LandNo1Block;
import net.mcreator.papercraftmagicdecoration.block.KnittedLeopardRugTailBlock;
import net.mcreator.papercraftmagicdecoration.block.KnittedLeopardRugBlock;
import net.mcreator.papercraftmagicdecoration.block.KeyUnderTheLakeBlock;
import net.mcreator.papercraftmagicdecoration.block.KaziLuckycatBlock;
import net.mcreator.papercraftmagicdecoration.block.JumboSalmonBlock;
import net.mcreator.papercraftmagicdecoration.block.GuangSBlock;
import net.mcreator.papercraftmagicdecoration.block.GoldMedalCoffeeBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.GiftFromKaziManorBlock;
import net.mcreator.papercraftmagicdecoration.block.FourthSteakBlock;
import net.mcreator.papercraftmagicdecoration.block.FourthSalmonBlock;
import net.mcreator.papercraftmagicdecoration.block.ForgetMeNotBlock;
import net.mcreator.papercraftmagicdecoration.block.FoamBoxWithDirtBlock;
import net.mcreator.papercraftmagicdecoration.block.FlyWhiskeyBlock;
import net.mcreator.papercraftmagicdecoration.block.FlowerFertilizerBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.FirstSteakBlock;
import net.mcreator.papercraftmagicdecoration.block.FirstSalmonBlock;
import net.mcreator.papercraftmagicdecoration.block.FireplaceDecorationBlock;
import net.mcreator.papercraftmagicdecoration.block.FireWhiskeyBlock;
import net.mcreator.papercraftmagicdecoration.block.FilledSporesCollectionPlateBlock;
import net.mcreator.papercraftmagicdecoration.block.FifthSteakBlock;
import net.mcreator.papercraftmagicdecoration.block.FerryWhiskeyBlock;
import net.mcreator.papercraftmagicdecoration.block.EmeraldBlueEarthTileBlock;
import net.mcreator.papercraftmagicdecoration.block.EdgedChalkboardBlock;
import net.mcreator.papercraftmagicdecoration.block.DwarfPlumBlossomBlock;
import net.mcreator.papercraftmagicdecoration.block.DirtHoleBlock;
import net.mcreator.papercraftmagicdecoration.block.DiplomaticoCoffeeBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.DewyMembraneBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.DevilMargaritaBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.CupboardBlock;
import net.mcreator.papercraftmagicdecoration.block.CottonSergeBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.CopperBartenderBlock;
import net.mcreator.papercraftmagicdecoration.block.CollarAndHandcuffsBlock;
import net.mcreator.papercraftmagicdecoration.block.CoffeePastinacaSativaSproutBlock;
import net.mcreator.papercraftmagicdecoration.block.CoffeePastinacaSativaSeededBlock;
import net.mcreator.papercraftmagicdecoration.block.CoffeePastinacaSativaRimBlock;
import net.mcreator.papercraftmagicdecoration.block.CoffeePastinacaSativaGrowBlock;
import net.mcreator.papercraftmagicdecoration.block.CoffeePastinacaSativaFruitingStemBlock;
import net.mcreator.papercraftmagicdecoration.block.CoffeePastinacaSativaFlowersBlock;
import net.mcreator.papercraftmagicdecoration.block.CoffeePastinacaSativaCoreBlock;
import net.mcreator.papercraftmagicdecoration.block.CanopyTreeTrunkBlock;
import net.mcreator.papercraftmagicdecoration.block.CanopyTreeMushroomBlock;
import net.mcreator.papercraftmagicdecoration.block.CanopyTreeLimbBlock;
import net.mcreator.papercraftmagicdecoration.block.CanopyTreeFoliageBlock;
import net.mcreator.papercraftmagicdecoration.block.CanopyTreeFernBlock;
import net.mcreator.papercraftmagicdecoration.block.CanopyTreeDroopingRootBlock;
import net.mcreator.papercraftmagicdecoration.block.CanopyTreeBudBlock;
import net.mcreator.papercraftmagicdecoration.block.BucketOfFriedChickenBlock;
import net.mcreator.papercraftmagicdecoration.block.BluePaperBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.BlueAndWhiteTileFooringBlock;
import net.mcreator.papercraftmagicdecoration.block.BloodyMaryBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.BlazewhiskeyBlock;
import net.mcreator.papercraftmagicdecoration.block.BlackPaperBlickBlock;
import net.mcreator.papercraftmagicdecoration.block.BlackAndWhiteTileFooringBlock;
import net.mcreator.papercraftmagicdecoration.block.AerogelBlock;
import net.mcreator.papercraftmagicdecoration.block.AGlassOfPoisonRumBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.AGlassOfLuckyCactusBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.AGlassOfLandNo1BlockBlock;
import net.mcreator.papercraftmagicdecoration.block.AGlassOfFlyWhiskeyBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.AGlassOfFerryWhiskeyBlockBlock;
import net.mcreator.papercraftmagicdecoration.block.AGlassOfBlazeWhiskeyBlockBlock;
import net.mcreator.papercraftmagicdecoration.PapercraftMagicDecorationMod;

public class PapercraftMagicDecorationModBlocks {
	public static final DeferredRegister<Block> REGISTRY = DeferredRegister.create(ForgeRegistries.BLOCKS, PapercraftMagicDecorationMod.MODID);
	public static final RegistryObject<Block> PAPER_CUTTING_TABLE = REGISTRY.register("paper_cutting_table", () -> new PaperCuttingTableBlock());
	public static final RegistryObject<Block> GIFT_FROM_KAZI_MANOR = REGISTRY.register("gift_from_kazi_manor", () -> new GiftFromKaziManorBlock());
	public static final RegistryObject<Block> KEY_UNDER_THE_LAKE = REGISTRY.register("key_under_the_lake", () -> new KeyUnderTheLakeBlock());
	public static final RegistryObject<Block> AEROGEL = REGISTRY.register("aerogel", () -> new AerogelBlock());
	public static final RegistryObject<Block> BLACK_PAPER_BLICK = REGISTRY.register("black_paper_blick", () -> new BlackPaperBlickBlock());
	public static final RegistryObject<Block> WHITE_PAPER_BLOCK = REGISTRY.register("white_paper_block", () -> new WhitePaperBlockBlock());
	public static final RegistryObject<Block> RED_PAPER_BLOCK = REGISTRY.register("red_paper_block", () -> new RedPaperBlockBlock());
	public static final RegistryObject<Block> BLUE_PAPER_BLOCK = REGISTRY.register("blue_paper_block", () -> new BluePaperBlockBlock());
	public static final RegistryObject<Block> YELLOW_PAPER_BLOCK = REGISTRY.register("yellow_paper_block", () -> new YellowPaperBlockBlock());
	public static final RegistryObject<Block> DEWY_MEMBRANE_BLOCK = REGISTRY.register("dewy_membrane_block", () -> new DewyMembraneBlockBlock());
	public static final RegistryObject<Block> COTTON_SERGE_BLOCK = REGISTRY.register("cotton_serge_block", () -> new CottonSergeBlockBlock());
	public static final RegistryObject<Block> KAZI_LUCKYCAT = REGISTRY.register("kazi_luckycat", () -> new KaziLuckycatBlock());
	public static final RegistryObject<Block> LOUD_BUTTON = REGISTRY.register("loud_button", () -> new LoudButtonBlock());
	public static final RegistryObject<Block> SILVER_FOOD_DOME = REGISTRY.register("silver_food_dome", () -> new SilverFoodDomeBlock());
	public static final RegistryObject<Block> FOAM_BOX_WITH_DIRT = REGISTRY.register("foam_box_with_dirt", () -> new FoamBoxWithDirtBlock());
	public static final RegistryObject<Block> WOODWORKING_TABLE = REGISTRY.register("woodworking_table", () -> new WoodworkingTableBlock());
	public static final RegistryObject<Block> LOWCABINET_WITH_TABLECLOTH = REGISTRY.register("lowcabinet_with_tablecloth", () -> new LowcabinetWithTableclothBlock());
	public static final RegistryObject<Block> WOODEN_BARREL_BOOKSHELF = REGISTRY.register("wooden_barrel_bookshelf", () -> new WoodenBarrelBookshelfBlock());
	public static final RegistryObject<Block> EDGED_CHALKBOARD = REGISTRY.register("edged_chalkboard", () -> new EdgedChalkboardBlock());
	public static final RegistryObject<Block> LONG_STORAGE_TABLE = REGISTRY.register("long_storage_table", () -> new LongStorageTableBlock());
	public static final RegistryObject<Block> CUPBOARD = REGISTRY.register("cupboard", () -> new CupboardBlock());
	public static final RegistryObject<Block> OLD_ORGAN = REGISTRY.register("old_organ", () -> new OldOrganBlock());
	public static final RegistryObject<Block> LARGE_DINING_TABLE = REGISTRY.register("large_dining_table", () -> new LargeDiningTableBlock());
	public static final RegistryObject<Block> RED_VELVET_CHAISE_LONGUE = REGISTRY.register("red_velvet_chaise_longue", () -> new RedVelvetChaiseLongueBlock());
	public static final RegistryObject<Block> BLACK_AND_WHITE_TILE_FOORING = REGISTRY.register("black_and_white_tile_fooring", () -> new BlackAndWhiteTileFooringBlock());
	public static final RegistryObject<Block> UNDERGROUND_PANELLING = REGISTRY.register("underground_panelling", () -> new UndergroundPanellingBlock());
	public static final RegistryObject<Block> UNDERGROUND_WALLPAPER_WALLS = REGISTRY.register("underground_wallpaper_walls", () -> new UndergroundWallpaperWallsBlock());
	public static final RegistryObject<Block> UNDERGROUND_DOOR_FRAMES = REGISTRY.register("underground_door_frames", () -> new UndergroundDoorFramesBlock());
	public static final RegistryObject<Block> PALM_TREE_CROWN = REGISTRY.register("palm_tree_crown", () -> new PalmTreeCrownBlock());
	public static final RegistryObject<Block> PALM_TREE_TOP = REGISTRY.register("palm_tree_top", () -> new PalmTreeTopBlock());
	public static final RegistryObject<Block> PALM_TREE_TRUNK_TOP = REGISTRY.register("palm_tree_trunk_top", () -> new PalmTreeTrunkTopBlock());
	public static final RegistryObject<Block> PALM_TREE_TRUNK = REGISTRY.register("palm_tree_trunk", () -> new PalmTreeTrunkBlock());
	public static final RegistryObject<Block> ROUGH_PALM_TREE_TRUNK = REGISTRY.register("rough_palm_tree_trunk", () -> new RoughPalmTreeTrunkBlock());
	public static final RegistryObject<Block> KNITTED_LEOPARD_RUG = REGISTRY.register("knitted_leopard_rug", () -> new KnittedLeopardRugBlock());
	public static final RegistryObject<Block> FIREPLACE_DECORATION = REGISTRY.register("fireplace_decoration", () -> new FireplaceDecorationBlock());
	public static final RegistryObject<Block> RUSTIC_BLUE_WALLPAPER_WALLS = REGISTRY.register("rustic_blue_wallpaper_walls", () -> new RusticBlueWallpaperWallsBlock());
	public static final RegistryObject<Block> RUSTIC_PANELLING = REGISTRY.register("rustic_panelling", () -> new RusticPanellingBlock());
	public static final RegistryObject<Block> BLUE_AND_WHITE_TILE_FOORING = REGISTRY.register("blue_and_white_tile_fooring", () -> new BlueAndWhiteTileFooringBlock());
	public static final RegistryObject<Block> STAR_EMBELLISHED_CEILING = REGISTRY.register("star_embellished_ceiling", () -> new StarEmbellishedCeilingBlock());
	public static final RegistryObject<Block> WINE_AROMA_RED_WALLPAPER_WALLS = REGISTRY.register("wine_aroma_red_wallpaper_walls", () -> new WineAromaRedWallpaperWallsBlock());
	public static final RegistryObject<Block> WINE_AROMA_BLUE_WALLPAPER_WALLS = REGISTRY.register("wine_aroma_blue_wallpaper_walls", () -> new WineAromaBlueWallpaperWallsBlock());
	public static final RegistryObject<Block> MARBLE_ANGEL = REGISTRY.register("marble_angel", () -> new MarbleAngelBlock());
	public static final RegistryObject<Block> EMERALD_BLUE_EARTH_TILE = REGISTRY.register("emerald_blue_earth_tile", () -> new EmeraldBlueEarthTileBlock());
	public static final RegistryObject<Block> CANOPY_TREE_TRUNK = REGISTRY.register("canopy_tree_trunk", () -> new CanopyTreeTrunkBlock());
	public static final RegistryObject<Block> CANOPY_TREE_DROOPING_ROOT = REGISTRY.register("canopy_tree_drooping_root", () -> new CanopyTreeDroopingRootBlock());
	public static final RegistryObject<Block> CANOPY_TREE_FOLIAGE = REGISTRY.register("canopy_tree_foliage", () -> new CanopyTreeFoliageBlock());
	public static final RegistryObject<Block> CANOPY_TREE_LIMB = REGISTRY.register("canopy_tree_limb", () -> new CanopyTreeLimbBlock());
	public static final RegistryObject<Block> CANOPY_TREE_FERN = REGISTRY.register("canopy_tree_fern", () -> new CanopyTreeFernBlock());
	public static final RegistryObject<Block> CANOPY_TREE_MUSHROOM = REGISTRY.register("canopy_tree_mushroom", () -> new CanopyTreeMushroomBlock());
	public static final RegistryObject<Block> DWARF_PLUM_BLOSSOM = REGISTRY.register("dwarf_plum_blossom", () -> new DwarfPlumBlossomBlock());
	public static final RegistryObject<Block> MINI_PALM_TREE = REGISTRY.register("mini_palm_tree", () -> new MiniPalmTreeBlock());
	public static final RegistryObject<Block> RAW_MANGA_MEAT = REGISTRY.register("raw_manga_meat", () -> new RawMangaMeatBlock());
	public static final RegistryObject<Block> MANGA_MEAT = REGISTRY.register("manga_meat", () -> new MangaMeatBlock());
	public static final RegistryObject<Block> BUCKET_OF_FRIED_CHICKEN = REGISTRY.register("bucket_of_fried_chicken", () -> new BucketOfFriedChickenBlock());
	public static final RegistryObject<Block> RAW_MONSTER_STEAK = REGISTRY.register("raw_monster_steak", () -> new RawMonsterSteakBlock());
	public static final RegistryObject<Block> JUMBO_SALMON = REGISTRY.register("jumbo_salmon", () -> new JumboSalmonBlock());
	public static final RegistryObject<Block> BLAZEWHISKEY = REGISTRY.register("blazewhiskey", () -> new BlazewhiskeyBlock());
	public static final RegistryObject<Block> FERRY_WHISKEY = REGISTRY.register("ferry_whiskey", () -> new FerryWhiskeyBlock());
	public static final RegistryObject<Block> RAW_SAUSAGE_MACE_WEAPON = REGISTRY.register("raw_sausage_mace_weapon", () -> new RawSausageMaceWeaponBlock());
	public static final RegistryObject<Block> FLY_WHISKEY = REGISTRY.register("fly_whiskey", () -> new FlyWhiskeyBlock());
	public static final RegistryObject<Block> LUCKY_CACTUS = REGISTRY.register("lucky_cactus", () -> new LuckyCactusBlock());
	public static final RegistryObject<Block> POISON_RUM = REGISTRY.register("poison_rum", () -> new PoisonRumBlock());
	public static final RegistryObject<Block> PACK_OF_GUANG_S = REGISTRY.register("pack_of_guang_s", () -> new PackOfGuangSBlock());
	public static final RegistryObject<Block> LAND_NO_1 = REGISTRY.register("land_no_1", () -> new LandNo1Block());
	public static final RegistryObject<Block> POT_OF_NOCTURNAL_CAT_COFFEE = REGISTRY.register("pot_of_nocturnal_cat_coffee", () -> new PotOfNocturnalCatCoffeeBlock());
	public static final RegistryObject<Block> POT_OF_BOILED_NOCTURNAL_CAT_COFFEE = REGISTRY.register("pot_of_boiled_nocturnal_cat_coffee", () -> new PotOfBoiledNocturnalCatCoffeeBlock());
	public static final RegistryObject<Block> POT_OF_GOLD_MEDAL_COFFEE = REGISTRY.register("pot_of_gold_medal_coffee", () -> new PotOfGoldMedalCoffeeBlock());
	public static final RegistryObject<Block> POT_OF_BOILED_GOLD_MEDAL_COFFEE = REGISTRY.register("pot_of_boiled_gold_medal_coffee", () -> new PotOfBoiledGoldMedalCoffeeBlock());
	public static final RegistryObject<Block> DIRT_HOLE = REGISTRY.register("dirt_hole", () -> new DirtHoleBlock());
	public static final RegistryObject<Block> COFFEE_PASTINACA_SATIVA_FLOWERS = REGISTRY.register("coffee_pastinaca_sativa_flowers", () -> new CoffeePastinacaSativaFlowersBlock());
	public static final RegistryObject<Block> FORGET_ME_NOT = REGISTRY.register("forget_me_not", () -> new ForgetMeNotBlock());
	public static final RegistryObject<Block> SPORES_COLLECTION_PLATE = REGISTRY.register("spores_collection_plate", () -> new SporesCollectionPlateBlock());
	public static final RegistryObject<Block> COPPER_BARTENDER = REGISTRY.register("copper_bartender", () -> new CopperBartenderBlock());
	public static final RegistryObject<Block> PAINTING_NO_1_BUNNY_MAID = REGISTRY.register("painting_no_1_bunny_maid", () -> new PaintingNo1BunnyMaidBlock());
	public static final RegistryObject<Block> PAINTING_NO_2_AOAO = REGISTRY.register("painting_no_2_aoao", () -> new PaintingNo2AoaoBlock());
	public static final RegistryObject<Block> PAINTING_NO_3_FIRST_ENCOUNTER = REGISTRY.register("painting_no_3_first_encounter", () -> new PaintingNo3FirstEncounterBlock());
	public static final RegistryObject<Block> COLLAR_AND_HANDCUFFS = REGISTRY.register("collar_and_handcuffs", () -> new CollarAndHandcuffsBlock());
	public static final RegistryObject<Block> MANGA_MEAT_GRILL = REGISTRY.register("manga_meat_grill", () -> new MangaMeatGrillBlock());
	public static final RegistryObject<Block> ORGAN_PLAYING = REGISTRY.register("organ_playing", () -> new OrganPlayingBlock());
	public static final RegistryObject<Block> FIRE_WHISKEY = REGISTRY.register("fire_whiskey", () -> new FireWhiskeyBlock());
	public static final RegistryObject<Block> VODKA = REGISTRY.register("vodka", () -> new VodkaBlock());
	public static final RegistryObject<Block> FIRST_STEAK = REGISTRY.register("first_steak", () -> new FirstSteakBlock());
	public static final RegistryObject<Block> SECOND_STEAK = REGISTRY.register("second_steak", () -> new SecondSteakBlock());
	public static final RegistryObject<Block> THIRD_STEAK = REGISTRY.register("third_steak", () -> new ThirdSteakBlock());
	public static final RegistryObject<Block> FOURTH_STEAK = REGISTRY.register("fourth_steak", () -> new FourthSteakBlock());
	public static final RegistryObject<Block> FIFTH_STEAK = REGISTRY.register("fifth_steak", () -> new FifthSteakBlock());
	public static final RegistryObject<Block> SIXTH_STEAK = REGISTRY.register("sixth_steak", () -> new SixthSteakBlock());
	public static final RegistryObject<Block> STEAK_TRAY = REGISTRY.register("steak_tray", () -> new SteakTrayBlock());
	public static final RegistryObject<Block> SALMON_HEAD = REGISTRY.register("salmon_head", () -> new SalmonHeadBlock());
	public static final RegistryObject<Block> FIRST_SALMON = REGISTRY.register("first_salmon", () -> new FirstSalmonBlock());
	public static final RegistryObject<Block> SECOND_SALMON = REGISTRY.register("second_salmon", () -> new SecondSalmonBlock());
	public static final RegistryObject<Block> THIRD_SALMON = REGISTRY.register("third_salmon", () -> new ThirdSalmonBlock());
	public static final RegistryObject<Block> FOURTH_SALMON = REGISTRY.register("fourth_salmon", () -> new FourthSalmonBlock());
	public static final RegistryObject<Block> SALMON_TRAY = REGISTRY.register("salmon_tray", () -> new SalmonTrayBlock());
	public static final RegistryObject<Block> SAUSAGE_MACE_WEAPON_BLOCK = REGISTRY.register("sausage_mace_weapon_block", () -> new SausageMaceWeaponBlockBlock());
	public static final RegistryObject<Block> A_GLASS_OF_BLAZE_WHISKEY_BLOCK = REGISTRY.register("a_glass_of_blaze_whiskey_block", () -> new AGlassOfBlazeWhiskeyBlockBlock());
	public static final RegistryObject<Block> A_GLASS_OF_LUCKY_CACTUS_BLOCK = REGISTRY.register("a_glass_of_lucky_cactus_block", () -> new AGlassOfLuckyCactusBlockBlock());
	public static final RegistryObject<Block> A_GLASS_OF_POISON_RUM_BLOCK = REGISTRY.register("a_glass_of_poison_rum_block", () -> new AGlassOfPoisonRumBlockBlock());
	public static final RegistryObject<Block> A_GLASS_OF_FLY_WHISKEY_BLOCK = REGISTRY.register("a_glass_of_fly_whiskey_block", () -> new AGlassOfFlyWhiskeyBlockBlock());
	public static final RegistryObject<Block> GUANG_S = REGISTRY.register("guang_s", () -> new GuangSBlock());
	public static final RegistryObject<Block> A_GLASS_OF_FERRY_WHISKEY_BLOCK = REGISTRY.register("a_glass_of_ferry_whiskey_block", () -> new AGlassOfFerryWhiskeyBlockBlock());
	public static final RegistryObject<Block> KNITTED_LEOPARD_RUG_TAIL = REGISTRY.register("knitted_leopard_rug_tail", () -> new KnittedLeopardRugTailBlock());
	public static final RegistryObject<Block> A_GLASS_OF_LAND_NO_1_BLOCK = REGISTRY.register("a_glass_of_land_no_1_block", () -> new AGlassOfLandNo1BlockBlock());
	public static final RegistryObject<Block> PAIR_OF_LAND_NO_1_BY_THE_GLASS = REGISTRY.register("pair_of_land_no_1_by_the_glass", () -> new PairOfLandNo1ByTheGlassBlock());
	public static final RegistryObject<Block> PAIR_OF_LAND_NO_1_BY_THE_GLASS_AFTER_MOVING = REGISTRY.register("pair_of_land_no_1_by_the_glass_after_moving", () -> new PairOfLandNo1ByTheGlassAfterMovingBlock());
	public static final RegistryObject<Block> FILLED_SPORES_COLLECTION_PLATE = REGISTRY.register("filled_spores_collection_plate", () -> new FilledSporesCollectionPlateBlock());
	public static final RegistryObject<Block> BLOODY_MARY_BLOCK = REGISTRY.register("bloody_mary_block", () -> new BloodyMaryBlockBlock());
	public static final RegistryObject<Block> COFFEE_PASTINACA_SATIVA_CORE = REGISTRY.register("coffee_pastinaca_sativa_core", () -> new CoffeePastinacaSativaCoreBlock());
	public static final RegistryObject<Block> COFFEE_PASTINACA_SATIVA_FRUITING_STEM = REGISTRY.register("coffee_pastinaca_sativa_fruiting_stem", () -> new CoffeePastinacaSativaFruitingStemBlock());
	public static final RegistryObject<Block> COFFEE_PASTINACA_SATIVA_RIM = REGISTRY.register("coffee_pastinaca_sativa_rim", () -> new CoffeePastinacaSativaRimBlock());
	public static final RegistryObject<Block> COFFEE_PASTINACA_SATIVA_SEEDED = REGISTRY.register("coffee_pastinaca_sativa_seeded", () -> new CoffeePastinacaSativaSeededBlock());
	public static final RegistryObject<Block> COFFEE_PASTINACA_SATIVA_SPROUT = REGISTRY.register("coffee_pastinaca_sativa_sprout", () -> new CoffeePastinacaSativaSproutBlock());
	public static final RegistryObject<Block> COFFEE_PASTINACA_SATIVA_GROW = REGISTRY.register("coffee_pastinaca_sativa_grow", () -> new CoffeePastinacaSativaGrowBlock());
	public static final RegistryObject<Block> DEVIL_MARGARITA_BLOCK = REGISTRY.register("devil_margarita_block", () -> new DevilMargaritaBlockBlock());
	public static final RegistryObject<Block> UMBRELLA_CASHEW = REGISTRY.register("umbrella_cashew", () -> new UmbrellaCashewBlock());
	public static final RegistryObject<Block> NOCTURNAL_CAT_COFFEE_BLOCK = REGISTRY.register("nocturnal_cat_coffee_block", () -> new NocturnalCatCoffeeBlockBlock());
	public static final RegistryObject<Block> GOLD_MEDAL_COFFEE_BLOCK = REGISTRY.register("gold_medal_coffee_block", () -> new GoldMedalCoffeeBlockBlock());
	public static final RegistryObject<Block> DIPLOMATICO_COFFEE_BLOCK = REGISTRY.register("diplomatico_coffee_block", () -> new DiplomaticoCoffeeBlockBlock());
	public static final RegistryObject<Block> UMBRELLA_CASHEW_FRUITING_STEM = REGISTRY.register("umbrella_cashew_fruiting_stem", () -> new UmbrellaCashewFruitingStemBlock());
	public static final RegistryObject<Block> FLOWER_FERTILIZER_BLOCK = REGISTRY.register("flower_fertilizer_block", () -> new FlowerFertilizerBlockBlock());
	public static final RegistryObject<Block> CANOPY_TREE_BUD = REGISTRY.register("canopy_tree_bud", () -> new CanopyTreeBudBlock());
}
